# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteLista
PathDefault =  ..\Fontes
err         =  ..\Err
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
TestLis
Lista

[BuildInicio]
/OUT:..\Exe\TesteLista.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
